package config

var AllKECMetricConfigs = []KscMetricConfig{
	{
		Namespace:        "KEC",
		MetricName:       "per.cpu.usage",
		MetricDesc:       "单核利用率",
		MetricType:       2,
		Labels:           []string{"type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load",
		MetricDesc:       "CPU负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "cpu.utilizition.total[,idle,avg1]",
		MetricDesc:       "CPU闲置率",
		MetricType:       2,
		Labels:           []string{"mode", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.util",
		MetricDesc:       "CPU利用率",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vfs.fs.size",
		MetricDesc:       "磁盘使用率",
		MetricType:       2,
		Labels:           []string{"mountpoint", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.read.ops",
		MetricDesc:       "磁盘每秒读次数盘符",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.write.ops",
		MetricDesc:       "磁盘每秒写次数盘符",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.read.Bps",
		MetricDesc:       "磁盘读盘符",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.write.Bps",
		MetricDesc:       "磁盘读盘符",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vm.memory.size",
		MetricDesc:       "总内存",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "B",
	},
	{
		Namespace:        "KEC",
		MetricName:       "memory.utilizition.total",
		MetricDesc:       "内存使用率",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.in",
		MetricDesc:       "网卡进流量",
		MetricType:       2,
		Labels:           []string{"device", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.out",
		MetricDesc:       "网卡出流量",
		MetricType:       2,
		Labels:           []string{"device", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.eip.out",
		MetricDesc:       "EIP方向",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.nat.out",
		MetricDesc:       "NAT方向",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.vpcintra.out",
		MetricDesc:       "VPC内部",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.4lbintra.out",
		MetricDesc:       "4层内网SLB",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.4lbextra.out",
		MetricDesc:       "4层公网SLB",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.7lbintra.out",
		MetricDesc:       "7层内网SLB",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.7lbextra.out",
		MetricDesc:       "7层公网SLB",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.foreign.out",
		MetricDesc:       "外部流量",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.endpoint.out",
		MetricDesc:       "终端子网",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.pubservice.out",
		MetricDesc:       "公共服务",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.4lbhealthcheck.out",
		MetricDesc:       "四层健康检查",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.7lbhealthcheck.out",
		MetricDesc:       "七层健康检查",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.nat.in.bps",
		MetricDesc:       "NAT入向",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.nat.out.bps",
		MetricDesc:       "NAT出向",
		MetricType:       2,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "tcp.count",
		MetricDesc:       "TCP连接数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KEC",
		MetricName:       "proc.num[]",
		MetricDesc:       "运行进程个数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KEC",
		MetricName:       "agent.ping",
		MetricDesc:       "宕机",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
}
