package config

var AllKECMetricConfigs = []KscMetricConfig{
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[percpu,avg1]",
		MetricDesc:       "CPU每核平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[percpu,avg5]",
		MetricDesc:       "CPU每核平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[percpu,avg15]",
		MetricDesc:       "CPU每核平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[all,avg1]",
		MetricDesc:       "CPU平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[all,avg5]",
		MetricDesc:       "CPU平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.load[all,avg15]",
		MetricDesc:       "CPU平均负载",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KEC",
		MetricName:       "cpu.utilizition.total[,idle,avg1]",
		MetricDesc:       "CPU闲置率",
		MetricType:       3,
		Labels:           []string{"mode", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "system.cpu.util",
		MetricDesc:       "CPU利用率",
		MetricType:       2,
		Labels:           []string{"type", "aggtype"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},

	{
		Namespace:        "KEC",
		MetricName:       "vfs.fs.size",
		MetricDesc:       "磁盘使用率",
		MetricType:       3,
		Labels:           []string{"mountpoint", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.read.ops",
		MetricDesc:       "磁盘每秒读次数盘符",
		MetricType:       3,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.write.ops",
		MetricDesc:       "磁盘每秒写次数盘符",
		MetricType:       3,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Ops",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.read.Bps",
		MetricDesc:       "磁盘读盘符",
		MetricType:       3,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "disk.write.Bps",
		MetricDesc:       "磁盘读盘符",
		MetricType:       3,
		Labels:           []string{"device"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vm.memory.size[available]",
		MetricDesc:       "可用内存",
		MetricType:       2,
		Labels:           []string{"type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "B",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vm.memory.size[total]",
		MetricDesc:       "总内存",
		MetricType:       2,
		Labels:           []string{"type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "B",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vm.memory.size[used]",
		MetricDesc:       "已用内存",
		MetricType:       2,
		Labels:           []string{"type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "B",
	},
	{
		Namespace:        "KEC",
		MetricName:       "vm.memory.size[pavailable]",
		MetricDesc:       "内存可用率",
		MetricType:       2,
		Labels:           []string{"type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "memory.utilizition.total",
		MetricDesc:       "内存使用率",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.in",
		MetricDesc:       "网卡进流量",
		MetricType:       3,
		Labels:           []string{"device", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "net.if.out",
		MetricDesc:       "网卡出流量",
		MetricType:       3,
		Labels:           []string{"device", "type"},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "Bps",
	},
	{
		Namespace:        "KEC",
		MetricName:       "tcp.count",
		MetricDesc:       "TCP连接数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KEC",
		MetricName:       "proc.num[]",
		MetricDesc:       "运行进程个数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KEC",
		MetricName:       "agent.ping",
		MetricDesc:       "宕机",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
}
