package config

var AllKS3MetricConfigs = []KscMetricConfig{
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.total.sd",
		MetricDesc:       "标准存储量总量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.add.sd",
		MetricDesc:       "标准存储量增量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.del.sd",
		MetricDesc:       "标准存储量删除量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.total.ia",
		MetricDesc:       "低频存储量总量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.add.ia",
		MetricDesc:       "低频存储量增量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.del.ia",
		MetricDesc:       "低频存储量删除量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.total.ar",
		MetricDesc:       "归档存储总量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.add.ar",
		MetricDesc:       "归档存储增量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.capacity.del.ar",
		MetricDesc:       "归档存储删除量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.down.sd",
		MetricDesc:       "标准存储流量（外网下载流量+CDN回源流量）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.onet.down.sd",
		MetricDesc:       "标准存储外网流量（不包含CDN下载量的公网下行流量）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.cdn.down.sd",
		MetricDesc:       "标准存储CDN流量（下载）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.down.ia",
		MetricDesc:       "低频存储流量（外网下载流量+CDN回源流量）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.onet.down.ia",
		MetricDesc:       "低频存储外网流量（不包含CDN下载量的公网下行流量）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.cdn.down.ia",
		MetricDesc:       "低频存储CDN流量（下载）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	{
		Namespace:        "KS3",
		MetricName:       "ks3.bucket.flow.down.ar",
		MetricDesc:       "归档存储流量（外网下载流量+CDN回源流量）",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "byte",
	},
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.flow.onet.down.ar",
	// 	MetricDesc:       "归档存储外网流量（不包含CDN下载量的公网下行流量）",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "byte",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.flow.cdn.down.ar",
	// 	MetricDesc:       "归档存储CDN流量（下载）",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "byte",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.bandwidth.down",
	// 	MetricDesc:       "下行带宽（不区分外网带宽和CDN回源带宽）",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "bps",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.getcount.sd",
	// 	MetricDesc:       "标准get次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.putcount.sd",
	// 	MetricDesc:       "标准put次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.getcount.ia",
	// 	MetricDesc:       "低频get次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.putcount.ia",
	// 	MetricDesc:       "低频put次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.getcount.ar",
	// 	MetricDesc:       "归档get次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.putcount.ar",
	// 	MetricDesc:       "归档put次数",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "次",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.flow.up.ia",
	// 	MetricDesc:       "低频存储取回量",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "byte",
	// },
	// {
	// 	Namespace:        "KS3",
	// 	MetricName:       "ks3.bucket.flow.up.ar",
	// 	MetricDesc:       "归档存储取回量",
	// 	MetricType:       1,
	// 	Labels:           []string{},
	// 	Statistics:       []string{"avg"},
	// 	MinPeriodSeconds: 60,
	// 	Unit:             "byte",
	// },
}
