package config

var AllKCMMetricConfigs = []KscMetricConfig{
	{
		Namespace:        "KCM",
		MetricName:       "node_arp_entries",
		MetricDesc:       "device的ARP表项",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_boot_time_seconds",
		MetricDesc:       "节点启动时间，unixtime",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_context_switches_total",
		MetricDesc:       "context switches（上下文切换）的总数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_cpu_guest_seconds_total",
		MetricDesc:       "每种模式在guests(VM)上花费CPU的秒数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_cpu_seconds_total",
		MetricDesc:       "在每种模式下花费CPU的秒数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_io_now",
		MetricDesc:       "当前正在进行的I/O数量",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_io_time_seconds_total",
		MetricDesc:       "执行I/O所花费的总时间",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_io_time_weighted_seconds_total",
		MetricDesc:       "进行I/O所花费的加权秒数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_read_bytes_total",
		MetricDesc:       "成功读取的总字节数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_read_time_seconds_total",
		MetricDesc:       "所有读取花费的总秒数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_reads_completed_total",
		MetricDesc:       "成功完成的读取总数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_reads_merged_total",
		MetricDesc:       "读合并的次数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_write_time_seconds_total",
		MetricDesc:       "所有写入花费的总秒数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_writes_completed_total",
		MetricDesc:       "成功完成的写入总数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_writes_merged_total",
		MetricDesc:       "写合并的次数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_disk_written_bytes_total",
		MetricDesc:       "成功写入的总字节数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_entropy_available_bits",
		MetricDesc:       "可用entropy的Bits（比特）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bits",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_exporter_build_info",
		MetricDesc:       "构建node_exporter的版本，修订版，分支和goversion标记，具有常量值“1”的metric",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filefd_allocated",
		MetricDesc:       "文件描述符统计：已分配",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filefd_maximum",
		MetricDesc:       "文件描述符统计：最大值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_avail_bytes",
		MetricDesc:       "非root用户可用的文件系统空间（以字节为单位）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_device_error",
		MetricDesc:       "获取指定设备的统计信息时是否发生错误",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_files",
		MetricDesc:       "文件系统总的file",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_files_free",
		MetricDesc:       "文件系统空闲file",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_free_bytes",
		MetricDesc:       "文件系统可用空间，以字节为单位",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_readonly",
		MetricDesc:       "文件系统只读状态",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_filesystem_size_bytes",
		MetricDesc:       "文件系统大小（字节）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_forks_total",
		MetricDesc:       "forks总数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_intr_total",
		MetricDesc:       "服务的中断总数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_load1",
		MetricDesc:       "1m负载平均值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_load15",
		MetricDesc:       "15m负载平均值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_load5",
		MetricDesc:       "5m负载平均值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "%",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Active_anon_bytes",
		MetricDesc:       "内存信息字段Active_anon_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Active_bytes",
		MetricDesc:       "内存信息字段Active_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Active_file_bytes",
		MetricDesc:       "内存信息字段Active_file_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_AnonHugePages_bytes",
		MetricDesc:       "内存信息字段AnonHugePages_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_AnonPages_bytes",
		MetricDesc:       "内存信息字段AnonPages_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Bounce_bytes",
		MetricDesc:       "内存信息字段Bounce_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Buffers_bytes",
		MetricDesc:       "内存信息字段Buffers_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Cached_bytes",
		MetricDesc:       "内存信息字段Cached_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_CmaFree_bytes",
		MetricDesc:       "内存信息字段CmaFree_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_CmaTotal_bytes",
		MetricDesc:       "内存信息字段CmaTotal_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_CommitLimit_bytes",
		MetricDesc:       "内存信息字段CommitLimit_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Committed_AS_bytes",
		MetricDesc:       "内存信息字段Committed_AS_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_DirectMap1G_bytes",
		MetricDesc:       "内存信息字段DirectMap1G_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_DirectMap2M_bytes",
		MetricDesc:       "内存信息字段DirectMap2M_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_DirectMap4k_bytes",
		MetricDesc:       "内存信息字段DirectMap4k_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Dirty_bytes",
		MetricDesc:       "内存信息字段Dirty_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_HardwareCorrupted_bytes",
		MetricDesc:       "内存信息字段HardwareCorrupted_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_HugePages_Free",
		MetricDesc:       "内存信息字段HugePages_Free",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_HugePages_Rsvd",
		MetricDesc:       "内存信息字段HugePages_Rsvd",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_HugePages_Surp",
		MetricDesc:       "内存信息字段HugePages_Surp",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_HugePages_Total",
		MetricDesc:       "内存信息字段HugePages_Total",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Hugepagesize_bytes",
		MetricDesc:       "内存信息字段Hugepagesize_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Inactive_anon_bytes",
		MetricDesc:       "内存信息字段Inactive_anon_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Inactive_bytes",
		MetricDesc:       "内存信息字段Inactive_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Inactive_file_bytes",
		MetricDesc:       "内存信息字段Inactive_file_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_KernelStack_bytes",
		MetricDesc:       "内存信息字段KernelStack_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Mapped_bytes",
		MetricDesc:       "内存信息字段Mapped_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_MemAvailable_bytes",
		MetricDesc:       "内存信息字段MemAvailable_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_MemFree_bytes",
		MetricDesc:       "内存信息字段MemFree_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_MemTotal_bytes",
		MetricDesc:       "内存信息字段MemTotal_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Mlocked_bytes",
		MetricDesc:       "内存信息字段Mlocked_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_NFS_Unstable_bytes",
		MetricDesc:       "内存信息字段NFS_Unstable_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_PageTables_bytes",
		MetricDesc:       "内存信息字段PageTables_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_SReclaimable_bytes",
		MetricDesc:       "内存信息字段SReclaimable_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_SUnreclaim_bytes",
		MetricDesc:       "内存信息字段SUnreclaim_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Shmem_bytes",
		MetricDesc:       "内存信息字段Shmem_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Slab_bytes",
		MetricDesc:       "内存信息字段Slab_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_SwapCached_bytes",
		MetricDesc:       "内存信息字段SwapCached_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_SwapFree_bytes",
		MetricDesc:       "内存信息字段SwapFree_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_SwapTotal_bytes",
		MetricDesc:       "内存信息字段SwapTotal_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Unevictable_bytes",
		MetricDesc:       "内存信息字段Unevictable_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_VmallocChunk_bytes",
		MetricDesc:       "内存信息字段VmallocChunk_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_VmallocTotal_bytes",
		MetricDesc:       "内存信息字段VmallocTotal_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_VmallocUsed_bytes",
		MetricDesc:       "内存信息字段VmallocUsed_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_WritebackTmp_bytes",
		MetricDesc:       "内存信息字段WritebackTmp_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_memory_Writeback_bytes",
		MetricDesc:       "内存信息字段Writeback_bytes",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp6_InErrors",
		MetricDesc:       "统计Icmp6InErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp6_InMsgs",
		MetricDesc:       "统计Icmp6InMsgs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp6_OutMsgs",
		MetricDesc:       "统计Icmp6OutMsgs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp_InErrors",
		MetricDesc:       "统计IcmpInErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp_InMsgs",
		MetricDesc:       "统计IcmpInMsgs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Icmp_OutMsgs",
		MetricDesc:       "统计IcmpOutMsgs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Ip6_InOctets",
		MetricDesc:       "统计Ip6InOctets",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Ip6_OutOctets",
		MetricDesc:       "统计Ip6OutOctets",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_IpExt_InOctets",
		MetricDesc:       "统计IpExtInOctets",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_IpExt_OutOctets",
		MetricDesc:       "统计IpExtOutOctets",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Ip_Forwarding",
		MetricDesc:       "统计IpForwarding",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_ListenDrops",
		MetricDesc:       "统计TcpExtListenDrops",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_ListenOverflows",
		MetricDesc:       "统计TcpExtListenOverflows",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_SyncookiesFailed",
		MetricDesc:       "统计TcpExtSyncookiesFailed",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_SyncookiesRecv",
		MetricDesc:       "统计TcpExtSyncookiesRecv",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_SyncookiesSent",
		MetricDesc:       "统计TcpExtSyncookiesSent",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_TcpExt_TCPSynRetrans",
		MetricDesc:       "统计TcpExtTCPSynRetrans",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_ActiveOpens",
		MetricDesc:       "统计TcpActiveOpens",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_CurrEstab",
		MetricDesc:       "统计TcpCurrEstab",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_InErrs",
		MetricDesc:       "统计TcpInErrs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_InSegs",
		MetricDesc:       "统计TcpInSegs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_OutSegs",
		MetricDesc:       "统计TcpOutSegs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_PassiveOpens",
		MetricDesc:       "统计TcpPassiveOpens",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Tcp_RetransSegs",
		MetricDesc:       "统计TcpRetransSegs",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp6_InDatagrams",
		MetricDesc:       "统计Udp6InDatagrams",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp6_InErrors",
		MetricDesc:       "统计Udp6InErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp6_NoPorts",
		MetricDesc:       "统计Udp6NoPorts",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp6_OutDatagrams",
		MetricDesc:       "统计Udp6OutDatagrams",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_UdpLite6_InErrors",
		MetricDesc:       "统计UdpLite6InErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_UdpLite_InErrors",
		MetricDesc:       "统计UdpLiteInErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp_InDatagrams",
		MetricDesc:       "统计UdpInDatagrams",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp_InErrors",
		MetricDesc:       "统计UdpInErrors",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp_NoPorts",
		MetricDesc:       "统计UdpNoPorts",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_netstat_Udp_OutDatagrams",
		MetricDesc:       "统计UdpOutDatagrams",
		MetricType:       3,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_address_assign_type",
		MetricDesc:       "/sys/class/net/<iface>/addr_assign_type值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_carrier",
		MetricDesc:       "/sys/class/net/<iface>/carrier值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_carrier_changes_total",
		MetricDesc:       "/sys/class/net/<iface>/carrier_changes值",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_device_id",
		MetricDesc:       "/sys/class/net/<iface>/dev_id值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_dormant",
		MetricDesc:       "/sys/class/net/<iface>/dormant（休眠）值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_flags",
		MetricDesc:       "/sys/class/net/<iface>/flags值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_iface_id",
		MetricDesc:       "/sys/class/net/<iface>/iface_id值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_iface_link",
		MetricDesc:       "/sys/class/net/<iface>/iface_link值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_iface_link_mode",
		MetricDesc:       "/sys/class/net/<iface>/iface_link_mode值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_info",
		MetricDesc:       "来自/sys/class/net/的非数字数据，值始终为1",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_mtu_bytes",
		MetricDesc:       "/sys/class/net/<iface>/mtu_bytes值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_net_dev_group",
		MetricDesc:       "/sys/class/net/<iface>/netdev_group值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_protocol_type",
		MetricDesc:       "/sys/class/net/<iface>/protocol_type值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_bytes_total",
		MetricDesc:       "网络设备已接收报文总字节数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_compressed_total",
		MetricDesc:       "网络设备统计信息receive_compressed",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_drop_total",
		MetricDesc:       "网络设备统计信息receive_drop",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_errs_total",
		MetricDesc:       "网络设备统计信息receive_errs",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_fifo_total",
		MetricDesc:       "网络设备统计信息receive_fifo",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_frame_total",
		MetricDesc:       "网络设备统计信息receive_frame",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_multicast_total",
		MetricDesc:       "网络设备统计信息receive_multicast",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_receive_packets_total",
		MetricDesc:       "网络设备已接收报文总数量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_speed_bytes",
		MetricDesc:       "网络设备速率（带宽）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "B/s",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_bytes_total",
		MetricDesc:       "网络设备已发送报文总字节数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "bytes",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_carrier_total",
		MetricDesc:       "网络设备统计信息transmit_carrier",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_colls_total",
		MetricDesc:       "网络设备统计信息transmit_colls",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_compressed_total",
		MetricDesc:       "网络设备统计信息transmit_compressed",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_drop_total",
		MetricDesc:       "网络设备统计信息transmit_drop",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_errs_total",
		MetricDesc:       "网络设备统计信息transmit_errs",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_fifo_total",
		MetricDesc:       "网络设备统计信息transmit_fifo",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_packets_total",
		MetricDesc:       "网络设备已发送报文总数量",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "count",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_transmit_queue_length",
		MetricDesc:       "网络设备发送报文队列长度",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_network_up",
		MetricDesc:       "如果operstate为’up’，则值为1，否则为0",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_procs_blocked",
		MetricDesc:       "阻塞等待I/O完成的进程数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_procs_running",
		MetricDesc:       "处于可运行状态的进程数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_scrape_collector_duration_seconds",
		MetricDesc:       "node_exporter：collector scrape持续时间",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_scrape_collector_success",
		MetricDesc:       "node_exporter：collector 是否成功",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_FRAG_inuse",
		MetricDesc:       "state inuse中的FRAG sockets数量",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_FRAG_memory",
		MetricDesc:       "state memory（状态存储器）中的FRAG sockets数量",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_RAW_inuse",
		MetricDesc:       "state inuse中的RAW sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_alloc",
		MetricDesc:       "state alloc中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_inuse",
		MetricDesc:       "state inuse中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_mem",
		MetricDesc:       "state mem中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_mem_bytes",
		MetricDesc:       "state mem_bytes中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_orphan",
		MetricDesc:       "state orphan中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_TCP_tw",
		MetricDesc:       "state tw中的TCP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_UDPLITE_inuse",
		MetricDesc:       "state inuse中的UDPLITE UDP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_UDP_inuse",
		MetricDesc:       "state inuse中的UDP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_UDP_mem",
		MetricDesc:       "state mem中的UDP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_UDP_mem_bytes",
		MetricDesc:       "state mem_bytes中的UDP sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_sockstat_sockets_used",
		MetricDesc:       "state used中的sockets sockets数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_textfile_scrape_error",
		MetricDesc:       "如果打开或读取文件时出错时为1，否则为0",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_time_seconds",
		MetricDesc:       "以纪元（1970年）开始的系统时间",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_estimated_error_seconds",
		MetricDesc:       "估计误差（秒）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_frequency_adjustment_ratio",
		MetricDesc:       "本地时钟频率调整",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_loop_time_constant",
		MetricDesc:       "锁相回路时间常数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_maxerror_seconds",
		MetricDesc:       "最大误差（秒）",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_offset_seconds",
		MetricDesc:       "本地系统和参考时钟之间的时间偏移",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_calibration_total",
		MetricDesc:       "每秒脉冲校准间隔计数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_error_total",
		MetricDesc:       "每秒脉冲校准错误计数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_frequency_hertz",
		MetricDesc:       "脉冲每秒频率",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_jitter_seconds",
		MetricDesc:       "脉冲每秒抖动",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_jitter_total",
		MetricDesc:       "每秒脉冲数超出抖动限制的事件数",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_shift_seconds",
		MetricDesc:       "每秒脉冲数超出稳定极限的事件数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_stability_exceeded_total",
		MetricDesc:       "每秒脉冲数超出稳定极限事件",
		MetricType:       1,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_pps_stability_hertz",
		MetricDesc:       "脉冲每秒稳定性，最近频率变化的平均值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_status",
		MetricDesc:       "status array bits的值",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_sync_status",
		MetricDesc:       "时钟与可靠服务器同步(1 = yes, 0 = no)",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_tai_offset_seconds",
		MetricDesc:       "国际原子时间（TAI）偏移量",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_timex_tick_seconds",
		MetricDesc:       "时钟周期之间的秒数",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_uname_info",
		MetricDesc:       "由uname系统调用提供的标记系统信息",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pgfault",
		MetricDesc:       "/proc/vmstat信息字段pgfault",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pgmajfault",
		MetricDesc:       "/proc/vmstat信息字段pgmajfault",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pgpgin",
		MetricDesc:       "/proc/vmstat信息字段pgpgin",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pgpgout",
		MetricDesc:       "/proc/vmstat信息字段pgpgout",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pswpin",
		MetricDesc:       "/proc/vmstat信息字段pswpin",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
	{
		Namespace:        "KCM",
		MetricName:       "node_vmstat_pswpout",
		MetricDesc:       "/proc/vmstat信息字段pswpout",
		MetricType:       2,
		Labels:           []string{},
		Statistics:       []string{"avg"},
		MinPeriodSeconds: 60,
		Unit:             "",
	},
}
